---
- name: Print K8S Credentials Information
  hosts: localhost
  gather_facts: false
  tasks:
    - name: t1
      debug:
        msg: "test1"

    - name: Retrieve and Print K8S API URL
      debug:
        msg: "K8S API URL: {{ lookup('env', 'API URL K8S') }}"

    - name: Retrieve and Print K8S Verify SSL Option
      debug:
        msg: "K8S Verify SSL: {{ lookup('env', 'K8S_VERIFY_SSL') }}"

    - name: Retrieve and Print K8S Token if provided
      debug:
        msg: "K8S Token: {{ lookup('env', 'K8S_TOKEN') }}"

    - name: Retrieve and Print K8S User
      debug:
        msg: "K8S User: {{ lookup('env', 'K8S_USER') }}"

    - name: Retrieve and Print K8S Password
      debug:
        msg: "K8S Password: {{ lookup('env', 'K8S_PASSWORD') }}"

    - name: Retrieve and Print K8S Namespace
      debug:
        msg: "K8S Namespace: {{ lookup('env', 'K8S_NAMESPACE') }}"
