
- name: Stampare le informazioni delle credenziali K8s
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Recupera le credenziali per l'API URL K8S
      set_fact:
        api_credential: "{{ lookup('env', 'CRED_TEST1') }}"
    - name: Debug API Credential
      debug:
        var: api_credential

    - name: Recupera le credenziali per K8s Credential
      set_fact:
        k8s_credential:
          user: "{{ lookup('env', 'USER') }}"
          password: "{{ lookup('env', 'PASSWORD') }}"
          namespace: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Stampa API URL K8S
      debug:
        msg: "API URL K8S: {{ api_credential }}"

    - name: Stampa User
      debug:
        msg: "User: {{ k8s_credential.user }}"

    - name: Stampa Password
      debug:
        msg: "Password: {{ k8s_credential.password }}"

    - name: Stampa Namespace
      debug:
        msg: "Namespace: {{ k8s_credential.namespace }}"
