
- name: Stampare le informazioni delle credenziali
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:

      - name: Stampa le informazioni della credenziale FC_TEST_K8S_CRED
        debug:
          msg:
            - "API URL K8S: {{ CUSTOM_API_URL_K8S }}"
            - "Verify SSL Option: {{ CUSTOM_VERIFY_SSL }}"
            - "User: {{ CUSTOM_K8S_USER }}"
            - "Password: {{ CUSTOM_K8S_PASSWORD }}"
            - "Namespace: {{ CUSTOM_K8S_NAMESPACE }}"